// Generated by Selenium IDE
const { Builder, By, Key, until, describe } = require("selenium-webdriver");
const assert = require("assert");

const driver = new Builder().forBrowser("chrome").build();

const main = async () => {
  try {
    await driver.get("https://outbound.nowports.com/dashboard");

    await driver.manage().window().setRect(1440, 900)
    // Login
    await driver.findElement(By.id("root-id-input")).sendKeys("antonio.galvan@nowports.com")
    await driver.findElement(By.css(".rott-input:nth-child(2) > #root-id-input")).sendKeys("ggaj1901227")
    await driver.findElement(By.className("submit-button-big")).click();

    await driver.wait(until.elementLocated(By.css(".submit-altern-button-big > .undefined")), 3000, "No encontro el boton");
    await driver.findElement(By.css(".submit-altern-button-big > .undefined")).click();

    await driver.wait(until.elementLocated(By.xpath(".//*[@id='root']/div/div/div[2]/div/div[2]/div[2]/div/div/div/div[3]/div/div/div/div[3]/div")), 4000, "No encontro el Aéreo");
    await driver.findElement(By.xpath(".//*[@id='root']/div/div/div[2]/div/div[2]/div[2]/div/div/div/div[3]/div/div/div/div[3]/div")).click();


    await driver.wait(until.elementLocated(By.css(".submit-button")), 4000, "No encontro el continuar");
    await driver.findElement(By.css(".submit-button")).click();


    await driver.wait(until.elementLocated(By.xpath("//*[@id='root']/div/div/div[2]/div/div[2]/div[2]/div/div/div/div[3]/div/div/div[1]/div[1]/div")), 4000, "No encontro el importación");
    await driver.findElement(By.xpath("//*[@id='root']/div/div/div[2]/div/div[2]/div[2]/div/div/div/div[3]/div/div/div[1]/div[1]/div")).click();

    {
      const element = await driver.findElement(
        By.xpath("/html/body/div[1]/div/div/div[2]/div/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div/div/div[2]/div/div")
      );
      element.click();
      // await driver
      //   .actions({ bridge: true })
      //   .moveToElement(element)
      //   .clickAndHold()
      //   .perform();
    }
    await driver.wait(until.elementLocated(By.xpath("/html/body/div[1]/div/div/div[2]/div/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div/div/div[2]/div/div")), 4000, "No encontro el selector");
    // {
    //   const element = await driver.findElement(
    //     By.id("react-select-5-option-0")
    //   );
    //   await driver
    //     .actions({ bridge: true })
    //     .moveToElement(element)
    //     .release()
    //     .perform();
    // }
    // await driver.findElement(By.id("origin-airport")).click();
    // await driver.findElement(By.id("react-select-5-option-73")).click();
    // {
    //   const element = await driver.findElement(
    //     By.css(".rotterdam__placeholder")
    //   );
    //   await driver
    //     .actions({ bridge: true })
    //     .moveToElement(element)
    //     .clickAndHold()
    //     .perform();
    // }
    // {
    //   const element = await driver.findElement(
    //     By.id("react-select-6-option-0")
    //   );
    //   await driver
    //     .actions({ bridge: true })
    //     .moveToElement(element)
    //     .release()
    //     .perform();
    // }
    // await driver.findElement(By.id("destination-airport")).click();
    // await driver.findElement(By.id("react-select-6-option-77")).click();
    // await driver
    //   .findElement(
    //     By.css(".ant-col:nth-child(2) > .button-wrapper > .submit-button")
    //   )
    //   .click();
    // await driver
    //   .findElement(
    //     By.css(".ant-col:nth-child(1) > .image-card-container > .text-section")
    //   )
    //   .click();
    // await driver
    //   .findElement(
    //     By.css(".ant-col:nth-child(2) > .button-wrapper > .submit-button")
    //   )
    //   .click();
    // {
    //   const element = await driver.findElement(
    //     By.css(".ant-col:nth-child(2) > .button-wrapper > .submit-button")
    //   );
    //   await driver.actions({ bridge: true }).moveToElement(element).perform();
    // }
    // {
    //   const element = await driver.findElement(By.CSS_SELECTOR, "body");
    //   await driver
    //     .actions({ bridge: true })
    //     .moveToElement(element, 0, 0)
    //     .perform();
    // }
    // await driver.findElement(By.css(".typehead-input")).click();
    // {
    //   const element = await driver.findElement(By.css(".addQuote-container"));
    //   await driver
    //     .actions({ bridge: true })
    //     .moveToElement(element)
    //     .release()
    //     .perform();
    // }
    await driver.close();
  } catch (e) {
    console.log("el error", e);
  } finally {
    await driver.quit();
    console.log("Done!");
  }
};

main().catch(console.error);
