// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('testoutbound', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('testoutbound', async function() {
    // Test name: testoutbound
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://outbound.nowports.com/")
    // 2 | setWindowSize | 1440x900 | 
    await driver.manage().window().setRect(1440, 900)
    // 3 | type | id=root-id-input | antonio.galvan@nowports.com
    await driver.findElement(By.id("root-id-input")).sendKeys("antonio.galvan@nowports.com")
    // 4 | type | css=.rott-input:nth-child(2) > #root-id-input | ggaj1901227
    await driver.findElement(By.css(".rott-input:nth-child(2) > #root-id-input")).sendKeys("ggaj1901227")
    // 5 | click | id=root-id-input | 
    await driver.findElement(By.id("root-id-input")).click()
    // 6 | click | css=.rott-input:nth-child(2) > #root-id-input | 
    await driver.findElement(By.css(".rott-input:nth-child(2) > #root-id-input")).click()
    // 7 | sendKeys | css=.rott-input:nth-child(2) > #root-id-input | ${KEY_ENTER}
    await driver.findElement(By.css(".rott-input:nth-child(2) > #root-id-input")).sendKeys(Key.ENTER)
    // 8 | type | css=.rott-input:nth-child(2) > #root-id-input | ggaj1901227
    await driver.findElement(By.css(".rott-input:nth-child(2) > #root-id-input")).sendKeys("ggaj1901227")
    // 9 | click | css=.submit-altern-button-big > .undefined | 
    await driver.findElement(By.css(".submit-altern-button-big > .undefined")).click()
    // 10 | click | css=.ant-col:nth-child(4) img | 
    await driver.findElement(By.css(".ant-col:nth-child(4) img")).click()
    // 11 | click | css=.submit-button | 
    await driver.findElement(By.css(".submit-button")).click()
    // 12 | click | css=.ant-col:nth-child(1) > .image-card-container img | 
    await driver.findElement(By.css(".ant-col:nth-child(1) > .image-card-container img")).click()
    // 13 | click | css=.rotterdam__value-container | 
    await driver.findElement(By.css(".rotterdam__value-container")).click()
    // 14 | click | id=react-select-4-option-2 | 
    await driver.findElement(By.id("react-select-4-option-2")).click()
    // 15 | click | css=.rotterdam__control--is-focused > .rotterdam__value-container | 
    await driver.findElement(By.css(".rotterdam__control--is-focused > .rotterdam__value-container")).click()
    // 16 | click | id=react-select-5-option-73 | 
    await driver.findElement(By.id("react-select-5-option-73")).click()
    // 17 | click | css=.rotterdam__placeholder | 
    await driver.findElement(By.css(".rotterdam__placeholder")).click()
    // 18 | click | id=react-select-6-option-77 | 
    await driver.findElement(By.id("react-select-6-option-77")).click()
    // 19 | click | css=.ant-col:nth-child(2) > .button-wrapper > .submit-button | 
    await driver.findElement(By.css(".ant-col:nth-child(2) > .button-wrapper > .submit-button")).click()
    // 20 | click | css=.typehead-input | 
    await driver.findElement(By.css(".typehead-input")).click()
    // 21 | mouseUp | css=.ant-col:nth-child(1) > .rott-select .rott-input-label | 
    {
      const element = await driver.findElement(By.css(".ant-col:nth-child(1) > .rott-select .rott-input-label"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
  })
})
